name: Generate Excel and Create Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag & release name (e.g. y9Ss.1)'
        required: true
      release_body:
        description: 'release notes'
        required: true
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Run Python Script
        env:
          GOOGLE_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
        run: uv run python generate_weapon_statistics_file.py ${{ github.event.inputs.tag_name }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          name: ${{ github.event.inputs.tag_name }}
          body: ${{ github.event.inputs.release_body }}
          files: rainbow-six-siege-weapon-statistics.xlsx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}